apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dso202-assignment-02
  labels:
    app.kubernetes.io/part-of: task-tracker
type: Opaque
data:
  DB_USER: dGFza3VzZXI=
  DB_PASSWORD: Q2hhbmdlTWUtU3RyMG5nIQ==
  POSTGRES_USER: dGFza3VzZXI=
  POSTGRES_PASSWORD: Q2hhbmdlTWUtU3RyMG5nIQ==
