apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dso202-assignment-02
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: task-tracker
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard      # kind's default provisioner
  resources:
    requests:
      storage: 1Gi
