apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: dso202-assignment-02
  labels: {app.kubernetes.io/part-of: task-tracker, tier: frontend}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: dso202-assignment-02
  labels: {app.kubernetes.io/part-of: task-tracker, tier: backend}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: dso202-assignment-02
  labels: {app.kubernetes.io/part-of: task-tracker, tier: database}
automountServiceAccountToken: false
